# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Validate YAML Files
on:
  push:
    branches: [main]



jobs:
  validate:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2.3.1

      - name: Validate YAML from Main
        uses: thiagodonferreira/yaml-schema-checker@main
        with:
          settingsFile: "schemas/deadlines.schema.json"
          jsonSchemas: |
            {
                "http://json.schemastore.org/composer": ["/*"],
                "file:///home/johnd/some-schema.json": ["some.yaml"],
                "../relative/path/schema.json": ["/config*.yaml"],
                "/Users/johnd/some-schema.json": ["some.yaml"],
            }

      # - name: yaml-schema-checker
      #   uses: thiagodonferreira/yaml-schema-checker@v0.0.3

      # - name: Validate YAML
      #   uses: brittonhayes/validate-yaml@v0.5.1
      #   with:
      #     schemaPath: "schemas/deadlines.schema.json"
      #     files: |
      #       data/deadlines/events/2022/ase-22.yml
